import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

interface PremiumContextType {
  isPremium: boolean;
  setPremiumStatus: (status: boolean) => void;
  permRequestsUsed: number;
  maxPermRequests: number;
  canGeneratePerm: boolean;
  incrementPermRequests: () => void;
  resetPermRequests: () => void;
  generatePerm: (course: any) => Promise<string>;
}

const PREMIUM_KEY = '@CourseSwipe:premiumStatus';
const PERM_REQUESTS_KEY = '@CourseSwipe:permRequestsUsed';

const PremiumContext = createContext<PremiumContextType | undefined>(undefined);

export function PremiumProvider({ children }: { children: ReactNode }) {
  const [isPremium, setIsPremium] = useState(false);
  const [permRequestsUsed, setPermRequestsUsed] = useState(0);
  const maxPermRequests = isPremium ? 50 : 3; // Free users get 3, premium get 50

  useEffect(() => {
    loadPremiumStatus();
    loadPermRequests();
  }, []);

  const loadPremiumStatus = async () => {
    try {
      const saved = await AsyncStorage.getItem(PREMIUM_KEY);
      if (saved === 'true') {
        setIsPremium(true);
      }
    } catch (error) {
      console.error('Error loading premium status:', error);
    }
  };

  const loadPermRequests = async () => {
    try {
      const saved = await AsyncStorage.getItem(PERM_REQUESTS_KEY);
      if (saved) {
        setPermRequestsUsed(parseInt(saved, 10));
      }
    } catch (error) {
      console.error('Error loading PERM requests:', error);
    }
  };

  const setPremiumStatus = async (status: boolean) => {
    setIsPremium(status);
    try {
      await AsyncStorage.setItem(PREMIUM_KEY, status.toString());
    } catch (error) {
      console.error('Error saving premium status:', error);
    }
  };

  const incrementPermRequests = async () => {
    const newCount = permRequestsUsed + 1;
    setPermRequestsUsed(newCount);
    try {
      await AsyncStorage.setItem(PERM_REQUESTS_KEY, newCount.toString());
    } catch (error) {
      console.error('Error saving PERM requests:', error);
    }
  };

  const resetPermRequests = async () => {
    setPermRequestsUsed(0);
    try {
      await AsyncStorage.removeItem(PERM_REQUESTS_KEY);
    } catch (error) {
      console.error('Error resetting PERM requests:', error);
    }
  };

  const canGeneratePerm = permRequestsUsed < maxPermRequests;

  const generatePerm = async (course: any): Promise<string> => {
    if (!canGeneratePerm) {
      throw new Error('PERM request limit reached. Upgrade to premium for more requests.');
    }

    // Simulate LLM API call - in production this would call OpenAI/Claude API
    await new Promise(resolve => setTimeout(resolve, 2000)); // Simulate API delay

    incrementPermRequests();

    // Generate a sophisticated PERM request
    const permText = `Dear Professor ${course.professor.replace('Prof. ', '')},

I hope this message finds you well. I am writing to request permission to enroll in ${course.courseCode}: ${course.title} for Spring 2025.

I am particularly drawn to this course because of its comprehensive coverage of ${course.description.split('.')[0].toLowerCase()}. My academic background and interests align well with the course objectives, and I believe this class would be instrumental in advancing my understanding of ${course.department.toLowerCase()}.

I have reviewed the course prerequisites${course.prerequisites ? ` (${course.prerequisites})` : ''} and confirm that I meet all requirements. I am prepared to fully engage with the coursework and contribute meaningfully to class discussions.

Given that the course is ${course.enrollmentCurrent === course.enrollmentCap ? 'currently full' : 'nearly at capacity'}, I would greatly appreciate your consideration for a PERM add. I am flexible with my schedule and committed to attending all sessions.

Thank you for your time and consideration. I look forward to the possibility of joining your class.

Best regards,
[Your Name]
[Your Email]
[Your Student ID]

---
Generated by CourseSwipe Premium ✨`;

    return permText;
  };

  return (
    <PremiumContext.Provider
      value={{
        isPremium,
        setPremiumStatus,
        permRequestsUsed,
        maxPermRequests,
        canGeneratePerm,
        incrementPermRequests,
        resetPermRequests,
        generatePerm,
      }}
    >
      {children}
    </PremiumContext.Provider>
  );
}

export function usePremium() {
  const context = useContext(PremiumContext);
  if (context === undefined) {
    throw new Error('usePremium must be used within a PremiumProvider');
  }
  return context;
}